In [6]:
import numpy as np

In [9]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [11]:
a_np = np.array([1,2,3,4,5])

In [14]:
a_np**2 #cleaner syntax -> ele wise operation

array([ 1,  4,  9, 16, 25], dtype=int32)

In [15]:
a_np**a_np

array([   1,    4,   27,  256, 3125], dtype=int32)

In [16]:
#speedtesting

In [17]:
l = range(1000000)

range(0, 1000000)

In [26]:
a = [i for i in range(1000000)]
%timeit [i**2 for i in a]

330 ms ± 7.89 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [27]:
l_np = np.array(range(1000000))

In [28]:
%timeit l_np**2

2.48 ms ± 66.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [54]:
td_arr = np.array([[1,2,3],[1,2,3],[2,3,4],[3,4,5]])
type(l_np)

numpy.ndarray

In [55]:
l_np.ndim #because its a 1D arr

1

In [56]:
td_arr.ndim #because its a 2D arr

2

In [67]:
td_arr.shape
# 1st dimension contain 4 elements 
# 2nd dimension contains 3 elements
# So dimensions are counted from outter to inner layer

(4, 3)

In [68]:
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,1,1],[2,2,2],[3,3,3]]])


In [69]:
arr2.shape

(2, 3, 3)

In [71]:
#you knw range...but ever heard of arange?
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [72]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [75]:
# incrementing by decimal..not possible in range
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [77]:
#arr are homogenous & 
#numpy will make it if its not

np.array([1,2,3,4.5])

array([1. , 2. , 3. , 4.5])

In [78]:
#because there's no loss of info

In [81]:
np.array([1,2,3,'A'])

array(['1', '2', '3', 'A'], dtype='<U11')

In [96]:
s_arr = np.array([1,2,3,4,5,6,7,8], dtype='float')

In [97]:
#lets see slicing & Indexing
s_arr[1:5]

array([2., 3., 4., 5.])

In [98]:
#multiple indexing
s_arr[[1,4,1]]

array([2., 5., 2.])

In [102]:
s_arr[-5:-1:-1] #going frm 4 to 8 in rev..not possible so empty 

array([], dtype=float64)

In [109]:
a=list(range(1,11)) #same in case of list btw
a[-5:-1:-1]

[]

In [111]:
#updating values
s_arr[5:] = 100
s_arr

array([  1.,   2.,   3.,   4.,   5., 100., 100., 100.])

In [113]:
#Fancy indexing (VERY IMP)

In [115]:
f_arr = np.arange(12)
f_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
f_arr < 5 #bool_mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False])

In [120]:
f_arr[f_arr < 5] #all true values are returned

array([0, 1, 2, 3, 4])

In [129]:
f_arr[f_arr % 2 == 0] #see how clean d syntax is..

array([ 0,  2,  4,  6,  8, 10])

In [130]:
#but wht if we hv multiple conditions?..
#first separate it then use bitwise operator because both the
#conditions are returning their resp. bool arrs
#so u cannot or them directly so rather use bitwise

f_arr[(f_arr % 2 == 0) | (f_arr % 5 == 0)]

array([ 0,  2,  4,  5,  6,  8, 10])

In [134]:
#vectorisation
np.arange(3) + 3

array([3, 4, 5])

In [141]:
#adding arr 5 elements each
a = np.arange(1,6)
b = np.arange(6,11)
a + b

array([ 7,  9, 11, 13, 15])

In [140]:
#error if lengths are unequal
a = np.arange(1,6)
b = np.arange(6,15)
a + b

ValueError: operands could not be broadcast together with shapes (5,) (9,) 

In [142]:
b

array([ 6,  7,  8,  9, 10])

In [143]:
np.mean(b)

8.0

In [144]:
np.min(b)

6

In [145]:
np.max(b)

10

In [146]:
np.sum(b)

40

In [149]:
np.add(b,10)

array([16, 17, 18, 19, 20])